name: 'terraform-pr-summary'
inputs:
  token:
    description: 'GitHub Token or PAT'
    required: true
    default: ''
  working-directory:
    description: 'Directory to run the action from'
    required: false
    default: '.'
  var-file:
    description: 'Optional tfvars file to use when running Terraform plan'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - run: |
        if [[ "${{ inputs.var-file }}" != "" ]]; then
          VAR_FILE_ARG="-var-file=${{ inputs.var-file }}"
        fi
        terraform plan $VAR_FILE_ARG -json > plan.json || true
        go run ${{ github.action_path }}/main.go plan.json ${{ github.event.pull_request.comments_url }} ${{ inputs.token }} ${{ inputs.var-file }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
