name: 'terraform-pr-summary'
description: Parses a Terraform plan file and adds a summary to a pull request
inputs:
  token:
    description: 'GitHub Token or PAT'
    default: ${{ github.token }}
  working-directory:
    description: 'Directory to run the action from'
    default: '.'
  plan-file:
    description: 'Terraform plan'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        terraform show -json ${{ inputs.plan-file }} > plan.json
        python ${{ github.action_path }}/parse_plan.py plan.json > summary.txt
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Terraform Plan

    - uses: peter-evans/create-or-update-comment@v3
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: ${{ inputs.working-directory }}/summary.txt
        edit-mode: replace
