name: 'terraform-pr-summary'
inputs:
  plan-file:
    description: 'The name of the Terraform plan file in JSON format'
    required: false
    default: 'plan.json'

runs:
  using: "composite"
  steps:
    - run: go run main.go ${{ inputs.plan-file }} ${{ github.event.pull_request.comments_url }} ${{ secrets.GITHUB_TOKEN }}
      working-directory: ${{ github.action_path }}
      shell: bash
