name: 'terraform-pr-summary'

runs:
  using: "composite"
  steps:
    - run: |
        terraform plan -json > plan.json || true
        go run main.go plan.json ${{ github.event.pull_request.comments_url }} ${{ secrets.GITHUB_TOKEN }}
      working-directory: ${{ github.action_path }}
      shell: bash
