name: plan

on:
  workflow_dispatch:
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false
      - name: init
        working-directory: test
        run: terraform init
      - uses: ./
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: test
          plan-file: test.plan
      - uses: ./
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: test
          plan-file: test.plan
          identifier: 'test1.tfvars'
      - uses: ./
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: test
          plan-file: test.plan
          identifier: 'test2.tfvars'