name: plan

on:
  workflow_dispatch:
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.1.4
          terraform_wrapper: false
      - name: init
        run: terraform init
      - uses: champ-oss/terraform-pr-summary@f033c3285f90b93004bc464c3e18cd5da7062aa9
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  plan-subdirectory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.1.4
          terraform_wrapper: false
      - name: init
        working-directory: test
        run: terraform init
      - uses: champ-oss/terraform-pr-summary@f033c3285f90b93004bc464c3e18cd5da7062aa9
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: test
          var-file: test.tfvars