name: plan

on:
  workflow_dispatch:
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.1.4
          terraform_wrapper: false
      - name: init
        run: terraform init
      - uses: ./
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  plan-subdirectory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.1.4
          terraform_wrapper: false
      - name: init
        working-directory: test
        run: terraform init
      - uses: ./
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: test
          var-file: test.tfvars