name: test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make lint
        if: ${{ always() }}
      - run: make check-coverage
        if: ${{ always() }}