name: test

on:
  workflow_dispatch:
  pull_request:

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_ORG: champ-oss
  SONAR_HOST_URL: https://sonarcloud.io

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: set-env-info
        run: echo "GIT_REPO=$(echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: make lint
        if: ${{ always() }}
      - run: make check-coverage
        if: ${{ always() }}
      - name: SonarCloud Scan
        if: ${{ always() }}
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectKey=${{ env.SONAR_ORG }}_${{ env.GIT_REPO }}
            -Dsonar.scm.provider=git
            -Dsonar.language=python
            -Dsonar.python.version=3.10
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.inclusions=**/**.py
            -Dsonar.exclusions=**/test*.py
            -Dsonar.test.inclusions=**/test*.py
            -Dsonar.pullrequest.github.repository=${{ github.repository }}
            -Dsonar.pullrequest.key=${{ github.event.number }}
            -Dsonar.pullrequest.branch=${{ github.HEAD_REF }}
            -Dsonar.pullrequest.base=${{ github.BASE_REF }}
            -Dsonar.python.coverage.reportPaths=coverage.xml